export enum StorageKey {
    DOMAIN = 'DOMAIN',
    PLENTY_ID = 'PLENTY_ID',
    SYNC_PATH = 'SYNC_PATH',
    SYNC_SELECTION = 'SYNC_SELECTION',
    SYNC_ATTRIBUTES = 'SYNC_ATTRIBUTES',
    LOGIN_DATA = 'LOGIN_DATA'
}
