name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [16]
        check-latest: [true]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: yarn
    - run: npm run lint
    - run: npm run test-headless
    - run: npm run build:prod
      env:
        CI: true

  dependency-review:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Dependency Review
          uses: actions/dependency-review-action@v1
